entrada = input("Digite algo: ")

print(f"O tipo primitivo desse valor é {type(entrada)}.")
print(f"Só tem espaços? {entrada.isspace()}")
print(f"É um número? {entrada.isnumeric()}")
print(f"É alfabético? {entrada.isalpha()}")
print(f"É alfanumérico? {entrada.isalnum()}")
print(f"Está em maiúsculas? {entrada.isupper()}")
print(f"Está em minúsculas? {entrada.islower()}")
print(f"Esta capitalizada? {entrada.istitle()}")
